on:
  workflow_dispatch:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main
      
    - name: Take a screenshot
      run: |
        # Make Bash print the commands as it is executing them
        set -x
        
        # Impersonate the GitHub Actions service account
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        # Run the workflow script
        google-chrome --screenshot="screenshot.png" --args --allow-file-access-from-files --headless --window-size=1920,240 "$PWD/index.html?demo"
        
        # Stage the Git index changes resulting from the CI script
        git add screenshot.png

    - name: Upload the screenshot to an artifact
      uses: actions/upload-artifact@v3
      with:
        name: screenshot.png
        path: screenshot.png

    - name: Upload the screenshot to the repository
      run: |
        # Commit the staged changes to the workflow repository
        git commit -m "Refresh the screenshot" -m "This screenshot was updated automatically using GitHub Actions"
        
        # Push the commit to the workflow repository
        git push
